[0m20:20:30.198038 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017291D35940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017291D359A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017291D35400>]}


============================== 20:20:30.203608 | 1f377f99-0bb3-485e-9fb8-cb9d9f6d5881 ==============================
[0m20:20:30.203608 [info ] [MainThread]: Running with dbt=1.9.7
[0m20:20:30.204606 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Marc Arguijo\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init Cadence', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:20:30.224300 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/Marc Arguijo/.dbt')}
[0m20:20:30.224300 [info ] [MainThread]: Creating dbt configuration folder at 
[0m20:20:30.226328 [debug] [MainThread]: Starter project path: C:\Users\Marc Arguijo\Development_Source\PowerBI_E2E_Report\.venv\Lib\site-packages\dbt\include\starter_project
[0m20:20:30.249239 [info ] [MainThread]: 
Your new dbt project "Cadence" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m20:20:30.249239 [info ] [MainThread]: Setting up your profile.
[0m20:25:10.476575 [error] [MainThread]: Encountered an error:

[0m20:25:10.479657 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Marc Arguijo\Development_Source\PowerBI_E2E_Report\.venv\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marc Arguijo\Development_Source\PowerBI_E2E_Report\.venv\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marc Arguijo\Development_Source\PowerBI_E2E_Report\.venv\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Marc Arguijo\Development_Source\PowerBI_E2E_Report\.venv\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\Marc Arguijo\Development_Source\PowerBI_E2E_Report\.venv\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\Marc Arguijo\Development_Source\PowerBI_E2E_Report\.venv\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\Marc Arguijo\Development_Source\PowerBI_E2E_Report\.venv\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marc Arguijo\Development_Source\PowerBI_E2E_Report\.venv\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\Marc Arguijo\Development_Source\PowerBI_E2E_Report\.venv\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marc Arguijo\Development_Source\PowerBI_E2E_Report\.venv\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m20:25:10.480682 [debug] [MainThread]: Command `dbt init` failed at 20:25:10.480682 after 280.62 seconds
[0m20:25:10.480682 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017292231AF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017293B8BEC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017293A3F530>]}
[0m20:25:10.480682 [debug] [MainThread]: Flushing usage events
[0m20:25:10.747619 [debug] [MainThread]: An error was encountered while trying to flush usage events
